### ISSUE TITLE
Issue with the XML launchfile mapper.launch

### ISSUE THREAD

**Issue by BenoitAud** [norlab-ulaval/mapper_config_template#2]
As discussed with Nicolas, launching mapper.launch does not seem to work. I made it work by editing lines 18 and 19 with this :
`<param name="save_map_cells_on_hard_drive" value="true"/>`
`<param name="publish_tfs_between_registrations" value="true"/>`
The XML tags were not formatted correctly.

**Comment by vineethak** [comment]
1) The documentation for the Norlab ICP Mapper ([link to docs](https://norlab-icp-mapper.readthedocs.io/en/latest/UsingInRos/)) references a file named mapper.launch.py. However, this file does not exist in the repository.
2) The XML tags in lines 18 and 19 are not formatted correctly; the issue was raised previously but remains unresolved.

**Comment by boxanm** [comment]
I think we will deprecate this repo and move the relevant launch file as an example to [norlab_icp_mapper_ros](https://github.com/norlab-ulaval/norlab_icp_mapper_ros/). For now, I'll update this repo with a `.launch.py` equivalent of the XML launch file
